---
title: "Python Lingo"
date: 2021-07-28T12:59:00-03:00
draft: false
---

Many terms here are not exclusive to Python, but some common terms have definitions that are specific to the Python community.

Also see the official https://docs.python.org/3/glossary.html[Python Glossary].

[glossary]

ABC (programming language):: (((ABC language)))A programming language created by Leo Geurts, Lambert Meertens, and Steven Pemberton. Guido van Rossum, who developed Python, worked as a programmer implementing the ABC environment in the 1980s. Block structuring by indentation, built-in tuples and dictionaries, tuple unpacking, the semantics of the `for` loop, and uniform handling of all sequence types are some of the distinctive characteristics of Python that came from ABC.

Abstract base class (ABC):: ((("ABC (Abstract Base Class)", "definition of term")))A class that cannot be instantiated, only subclassed. ABCs are how interfaces are formalized in Python. Instead of inheriting from an ABC, a class may also declare that it fulfills the interface by registering with the ABC to become a _virtual subclass_.

accessor:: (((accessor methods)))(((methods, accessor)))(((mutators)))A method implemented to provide access to a single data attribute. Some authors use _accessor_ as a generic term encompassing getter and setter methods, others use it to refer only to getters, referring to setters as mutators.

[[alias]]alias:: (((alias)))An alternative name for an object. For example, in `a = []; b = a` the variable `b` is an alias to the list bound to `a`.

aliasing:: (((aliasing)))Binding two or more names to the same object. Aliasing happens naturally all the time in any language where variables hold references to objects. To avoid confusion, just forget the idea that variables are boxes that store objects (an object can't be in two boxes at the same time). It's better to think of them as labels attached to objects (an object can have more than one label). See <<alias>>.

argument:: (((arguments, definition of term)))An expression passed to a function when it is called. In Pythonic parlance, _argument_ and <<parameter>> are almost always synonyms. See <<parameter>> for more about the distinction and usage of these terms.

attribute:: (((attributes, definition of term)))Methods and data attributes (i.e., "fields" in Java terms) are all known as attributes in Python. A method is just an attribute that happens to be a callable object (usually a function, but not necessarily).

BDFL:: ((("BDFL (Benevolent Dictator For Life)")))Benevolent Dictator For Life, alias for Guido van Rossum, creator of the Python language.

binary sequence:: (((binary sequences, definition of term)))(((sequences, binary)))Generic term for sequence types with byte elements. The built-in binary sequence types are `byte`, `bytearray`, and `memoryview`.

BOM:: ((("BOM (Byte Order Mark)")))Byte Order Mark, a sequence of bytes that may be present at the start of a UTF-16 encoded file. A BOM is the character U+FEFF (`ZERO WIDTH NO-BREAK SPACE`) encoded to produce either `b'\xfe\xff'` on a big-endian CPU, or `b'\xff\xfe'` on a little-endian one. Because there is no U+FFFE characer in Unicode, the presence of these bytes unambiguously reveals the byte ordering used in the encoding. Although redundant, a BOM encoded as `b'\xef\xbb\xbf'` may be found in UTF-8 files.

bound method:: (((bound methods)))(((methods, bound)))A method that is accessed through an instance becomes bound to that instance. Any method is actually a descriptor and when accessed, it returns itself wrapped in an object that binds the method to the instance. That object is the bound method. It can be invoked without passing the value of `self`. For example, given the assignment `my_method = my_obj.method`, the bound method can later be called as `my_method()`. Contrast with _unbound method_.

built-in function (BIF):: ((("BIF", see="built-in functions")))((("built-in functions")))((("functions", "built-in")))A function bundled with the Python interpreter, coded in the underlying implementation language (i.e., C for CPython; Java for Jython, and so on). The term often refers only to the functions that don't need to be imported, documented in http://docs.python.org/library/functions.html[Chapter 2, "Built-in Functions,"] of The Python Standard Library Reference. But built-in modules like `sys`, `math`, `re`, etc. also contain built-in functions.

byte string:: (((byte strings)))An unfortunate name still used to refer to `bytes` or `bytearray` in Python 3. In Python 2, the `str` type was really a byte string, and the term made sense to distinguish `str` from `unicode` strings. In Python 3, it makes no sense to insist on this term, and I tried to use _byte sequence_ whenever I needed to talk in general about...byte sequences.

bytes-like object:: ((("bytes-like objects")))(((objects, bytes-like)))A generic sequence of bytes. The most common bytes-like types are `bytes`, `bytearray`, and `memoryview` but other objects supporting the low-level CPython buffer protocol also qualify, if their elements are single bytes.

callable object:: ((("callable objects")))(((objects, callable)))An object that can be invoked with the call operator `()`, to return a result or to perform some action. There are nine flavors of callable objects in Python: user-defined functions, built-in functions, built-in methods, instance methods, generator functions, asynchronous generator functions, coroutines, classes, and instances of classes that implement the `+__call__+` special method.

CamelCase:: ((("CamelCase")))The convention of writing identifiers by joining words with uppercased initials (e.g., `ConnectionRefusedError`). PEP-8 recommends class names should be written in CamelCase, but the advice is not followed by the Python standard library. See <<snake_case>>.

Cheese Shop:: ((("Cheese Shop")))Original name of the https://pypi.python.org/pypi[Python Package Index] (PyPI), after the Monty Python skit about a cheese shop where nothing is available. As of this writing, the alias https://cheeseshop.python.org still works. See <<PyPI>>.

class:: (((classes, definition of term)))A program construct defining a new type, with data attributes and methods specifying possible operations on them. See `type`.

code point:: (((code point)))An integer in the range 0 to 0x10FFFF used to identify an entry in the Unicode character database. As of Unicode 7.0, less than 3% of all code points are assigned to characters. In the Python documentation, the term may be spelled as one or two words. For example, in http://docs.python.org/library/functions.html[Chapter 2, "Built-in Functions,"] of the _Python Library Reference_, the `chr` function is said to take an integer "codepoint," while its inverse, `ord`, is described as returning a "Unicode code point."

code smell:: ((("code smell")))A coding pattern that suggests there may be something wrong with the design of a program. For example, excessive use of `isinstance` checks against concrete classes is a code smell, as it makes the program harder to extend to deal with new types in the future.

codec:: (encoder/decoder) ((("codec module")))A module with functions to encode and decode, usually from `str` to `bytes` and back, although Python has a few codecs that perform `bytes` to `bytes` and `str` to `str` transformations.

collection:: (((collections, definition of term)))Generic term for data structures made of items that can be accessed individually. Some collections can contain objects of arbitrary types (see <<container>>) and others only objects of a single atomic type (see <<flat sequence>>). `list` and `bytes` are both collections, but `list` is a container, and `bytes` is a flat sequence.

considered harmful:: ((("&#x0022;Considered Harmful&#x0022; article", sortas="Considered Harmful")))Edsger Dijkstra's letter titled "Go To Statement Considered Harmful" established a formula for titles of essays criticizing some computer science technique. Wikipedia's http://en.wikipedia.org/wiki/Considered_harmful["Considered harmful" article] lists several examples, including http://meyerweb.com/eric/comment/chech.html["'Considered Harmful' Essays Considered Harmful"] by Eric A. Meyer.

constructor:: ((("constructors, definition of term")))Informally, the `+__init__+` instance method of a class is called its constructor, because its semantics is similar to that of a Java constructor. A better term for `+__init__+` is _initializer_, as the method does not actually build the instance, but receives it as its `self` argument. The _constructor_ term better describes the `+__new__+` class method, which Python calls before `+__init__+`, and is responsible for actually creating an instance and returning it. See <<initializer>>.

[[container]]container:: ((("containers, definition of term")))An object that holds references to other objects. Most collection types in Python are containers, but some are not. Contrast with _flat sequence_, which are collections but not containers.

context manager:: (((context managers, definition of term)))(((objects, context managers)))An object implementing both the `+__enter__+` and `+__exit__+` special methods, for use in a `with` block.

coroutine:: (((coroutines, definition of term)))A generator used for concurrent programming by receiving values from a scheduler or an event loop via `coro.send(value)`. The term may be used to describe the generator function or the generator object obtained by calling the generator function. See <<generator>>.

CPython:: (((CPython)))The standard Python interpreter, implemented in C. This term is only used when discussing implementation-specific behavior, or when talking about the multiple Python interpreters available, such as _PyPy_.

CRUD:: ((("CRUD (Create, Read, Update, and Delete)")))Acronym for Create, Read, Update, and Delete, the four basic functions in any application that stores records.

decorator:: (((decorators and closures, definition of decorators)))(((objects, decorators)))A callable object `A` that returns another callable object `B` and is invoked in code using the syntax `@A` right before the definition of a callable `C`. When reading such code, the Python interpreter invokes `A(C)` and binds the resulting `B` to the variable previously assigned to `C`, effectively replacing the definition of `C` with `B`. If the target callable `C` is a function, then `A` is a function decorator; if `C` is a class, then `A` is a class decorator.

deep copy:: (((deep copies)))(((objects, deep copies of)))A copy of an object in which all the objects that are attributes of the object are themselves also copied. Contrast with _shallow copy_.

descriptor:: (((descriptors, definition of term)))(((classes, descriptor)))A class implementing one or more of the `+__get__+`, `+__set__+`, or `+__delete__+` special methods becomes a descriptor when one of its instances is used as a class attribute of another class, the _managed class_. Descriptors manage the access and deletion of _managed attributes_ in the _managed class_, often storing data in the _managed instances_.

docstring:: ((("docstrings (documentation strings)")))Short for documentation string. When the first statement in a module, class, or function is a string literal, it is taken to be the _docstring_ for the enclosing object, and the interpreter saves it as the `+__doc__+` attribute of that object. See also _doctest_.

doctest:: ((("doctest testing package", "definition of term")))A module with functions to parse and run examples embedded in the docstrings of Python modules or in plain-text files. May also be used from the command line as:
+
----
python -m doctest
module_with_tests.py
----

DRY:: ((("DRY (Don't Repeat Yourself) principle")))Don't Repeat Yourself--a software engineering principle stating that "Every piece of knowledge must have a single, unambiguous, authoritative representation within a system." It first appeared in the book _The Pragmatic Programmer_ by Andy Hunt and Dave Thomas (Addison-Wesley, 1999).

duck typing:: (((duck typing, definition of term)))A form of polymorphism where functions operate on any object that implements the appropriate methods, regardless of their classes or explicit interface declarations.

dunder:: ((("double underscore (dunder)")))Shortcut to pronounce the names of _special methods_ and attributes that are written with leading and trailing double-underscores (i.e., `+__len__+` is read as "dunder len").

dunder method:: See _dunder_ and _special methods_.

EAFP:: ((("EAFP principle")))Acronym standing for the quote "It's easier to ask forgiveness than permission," attributed to computer pioneer Grace Hopper, and quoted by Pythonistas referring to dynamic programming practices like accessing attributes without testing first if they exist, and then catching the exception when that is the case. The docstring for the `hasattr` function actually says that it works "by calling getattr(object, name) and catching AttributeError."

eager:: (((eager objects)))(((objects, eager)))An iterable object that builds all its items at once. In Python, a _list comprehension_ is eager. Contrast with _lazy_.

fail-fast:: (((fail-fast design)))A systems design approach recommending that errors should be reported as early as possible. Python adheres to this principle more closely than most dynamic languages. For example, there is no "undefined" value: variables referenced before initialization generate an error, and `my_dict[k]` raises an exception if `k` is missing (in contrast with JavaScript). As another example, parallel assignment via tuple unpacking in Python only works if every item is explicitly handled, while Ruby silently deals with item count mismatches by ignoring unused items on the right side of the `=`, or by assigning `nil` to extra variables on the left side.

falsy:: (((falsiness)))Any value `x` for which `bool(x)` returns `False`; Python implicitly uses `bool` to evaluate objects in Boolean contexts, such as the expression controlling an `if` or `while` loop. The opposite of _truthy_.

file-like object:: (((file-like objects)))(((objects, file-like)))Used informally in the official documentation to refer to objects implementing the file protocol, with methods such as `read`, `write`, `close`, etc. Common variants are text files containing encoded strings with line-oriented reading and writing, `StringIO` instances which are in-memory text files, and binary files, containing unencoded bytes. The latter may be buffered or unbuffered. ABCs for the standard file types are defined in the `io` module since Python 2.6.

first-class function:: ((("first-class functions", "definition of term")))(((functions, first-class)))Any function that is a first-class object in the language (i.e., can be created at runtime, assigned to variables, passed as an argument, and returned as the result of another function). Python functions are first-class functions.

[[flat sequence]]flat sequence:: (((flat sequences)))(((sequences, flat)))A sequence type that physically stores the values of its items, and not references to other objects. The built-in types `str`, `bytes`, `bytearray`, `memoryview`, and `array.array` are flat sequences. Contrast with `list`, `tuple`, and `collections.deque`, which are container sequences. See _container_.

function:: (((functions, definition of term)))Strictly, an object resulting from evaluation of a +def+ block or a +lambda+ expression. Informally, the word _function_ is used to describe any callable object, such as methods and even classes sometimes. The official http://docs.python.org/library/functions.html[Built-in Functions] list includes several built-in classes like `dict`, `range`, and `str`. Also see _callable object_.

genexp:: Short for _generator expression_.

[[generator]]generator:: (((generators, definition of term)))An iterator built with a generator function or a generator expression that may produce values without necessarily iterating over a collection; the canonical example is a generator to produce the Fibonacci series which, because it is infinite, would never fit in a collection. The term is sometimes used to describe a _generator function_, besides the object that results from calling it.

generator function:: (((generator functions, definition of term)))(((functions, generator)))A function that has the `yield` keyword in its body. When invoked, a generator function returns a _generator_.

generator expression:: ((("generator expressions (genexps)", "definition of term")))An expression enclosed in parentheses using the same syntax of a _list comprehension_, but returning a generator instead of a list. A _generator expression_ can be understood as a _lazy_ version of a _list comprehension_. See _lazy_.

generic function:: (((generic functions)))(((functions, generic)))A group of functions designed to implement the same operation in customized ways for different object types. As of Python 3.4, the `functools.singledispatch` decorator is the standard way to create generic functions. This is known as multimethods in other languages.

GoF book:: ((("GoF (Gang of Four)")))Alias for _Design Patterns: Elements of Reusable Object-Oriented Software_ (Addison-Wesley, 1995), authored by the so-called Gang of Four (GoF): Erich Gamma, Richard Helm, Ralph Johnson, and John Vlissides.

hashable:: (((hashable objects)))(((objects, hashable)))An object is hashable if it has both `+__hash__+` and `+__eq__+` methods, with the constraints that the hash value must never change and if `a == b` then `hash(a) == hash(b)` must also be `True`. Most immutable built-in types are hashable, but a tuple is only hashable if every one of its items is also hashable.

higher-order function:: (((higher-order functions)))(((functions, higher-order)))A function that takes another function as argument, like `sorted`, `map`, and `filter`, or a function that returns a function as result, as Python decorators do.

idiom:: ((("idiom, definition of term")))"A manner of speaking that is natural to native speakers of a language," according to the Princeton WordNet.

import time:: (((import time)))The moment of initial execution of a module when its code is loaded by the Python interpreter, evaluated from top to bottom, and compiled into bytecode. This is when classes and functions are defined and become live objects. This is also when decorators are executed.

[[initializer]]initializer:: ((("initializers, definition of term")))A better name for the `+__init__+` method (instead of _constructor_). Initializing the instance received as `self` is the task of `+__init__+`. Actual instance construction is done by the `+__new__+` method. See _constructor_.

iterable:: (((iterable objects)))(((objects, iterable)))Any object from which the `iter` built-in function can obtain an iterator. An iterable object works as the source of items in +for+ loops, comprehensions, and tuple unpacking. Objects implementing an `+__iter__+` method returning an _iterator_ are iterable. Sequences are always iterable; other objects implementing a `+__getitem__+` method may also be iterable.

iterable unpacking:: (((iterable unpacking)))A modern, more precise synonym for _tuple unpacking_. See also _parallel assignment_.

iterator:: (((iterators, definition of term)))(((objects, iterators)))Any object that implements the `+__next__+` no-argument method, which returns the next item in a series, or raises `StopIteration` when there are no more items. Python iterators also implement the `+__iter__+` method so they are also _iterable_. Classic iterators, according to the original design pattern, return items from a collection. A _generator_ is also an _iterator_, but it's more flexible. See _generator_.

KISS principle:: ((("KISS (Keep It Simple, Stupid) principle")))The acronym stands for "Keep It Simple, Stupid." This calls for seeking the simplest possible solution, with the fewest moving parts. The phrase was coined by Kelly Johnson, a highly accomplished aerospace engineer who worked in the real Area 51 designing some of the most advanced aircraft of the 20th century.

lazy:: (((lazy objects)))(((objects, lazy)))An iterable object that produces items on demand. In Python, generators are lazy. Contrast _eager_.

listcomp:: Short for _list comprehension_.

list comprehension:: ((("list comprehensions (listcomps)", "definition of term")))An expression enclosed in brackets that uses the `for` and `in` keywords to build a list by processing and filtering the elements from one or more iterables. A list comprehension works eagerly. See _eager_.

liveness:: (((liveness property)))An asynchronous, threaded, or distributed system exhibits the liveness property when "something good eventually happens" (i.e., even if some expected computation is not happening right now, it will be completed eventually). If a system deadlocks, it has lost its liveness.

magic method:: Same as _special method_.

managed attribute:: (((managed attributes)))(((attributes, managed)))A public attribute managed by a descriptor object. Although the _managed attribute_ is defined in the _managed class_, it operates like an instance attribute (i.e., it usually has a value per instance, held in a _storage attribute_). See _descriptor_.

managed class:: (((managed classes)))(((classes, managed)))A class that uses a descriptor object to manage one of its attributes. See _descriptor_.

managed instance:: (((managed instances)))(((instances, managed)))An instance of a _managed class_. See _managed attribute_ and _descriptor_.

metaclass:: (((metaclasses, definition of term)))(((classes, metaclasses)))A class whose instances are classes. By default, Python classes are instances of `type`, for example, `type(int)` is the class `type`, therefore `type` is a metaclass. User-defined metaclasses can be created by subclassing `type`.

metaprogramming:: ((("metaprogramming")))The practice of writing programs that use runtime information about themselves to change their behavior. For example, an _ORM_ may introspect model class declarations to determine how to validate database record fields and convert database types to Python types.

monkey patching:: ((("monkey patching")))Dynamically changing a module, class, or function at runtime, usually to add features or fix bugs. Because it is done in memory and not by changing the source code, a monkey patch only affects the currently running instance of the program. Monkey patches break encapsulation and tend to be tightly coupled to the implementation details of the patched code units, so they are seen as temporary workarounds and not a recommended technique for code integration.

mixin class:: (((mixin classes)))(((classes, mixin)))A class designed to be subclassed together with one or more additional classes in a multiple-inheritance class tree. A mixin class should never be instantiated, and a concrete subclass of a mixin class should also subclass another nonmixin class.

mixin method:: (((mixin methods)))(((methods, mixin)))A concrete method implementation provided in an ABC or in a _mixin class_.

mutator:: See _accessor_.

name mangling:: (((name mangling)))The automatic renaming of private attributes from `+__x` to `_MyClass__x`, performed by the Python interpreter at runtime.

nonoverriding descriptor:: ((("nonoverriding descriptors")))(((descriptors, nonoverriding)))A _descriptor_ that does not implement `+__set__+` and therefore does not interfere with setting of the _managed attribute_ in the _managed instance_. Consequently, if a namesake attribute is set in the _managed instance_, it will shadow the descriptor in that instance. Also called nondata descriptor or shadowable descriptor. Contrast with _overriding descriptor_.

ORM:: ((("ORM (Object-Relational Mapper)")))Object-Relational Mapper--an API that provides access to database tables and records as Python classes and objects, providing method calls to perform database operations. SQLAlchemy is a popular standalone Python ORM; the Django and Web2py  frameworks have their own bundled ORMs.

overriding descriptor:: ((("overriding descriptors")))(((descriptors, overriding)))A _descriptor_ that implements `+__set__+` and therefore intercepts and overrides attempts at setting the _managed attribute_ in the _managed instance_. Also called data descriptor or enforced descriptor. Contrast with _non-overriding descriptor_.

parallel assignment:: (((parallel assignment)))(((destructuring assignment)))(((assignment, parallel)))(((assignment, destructuring)))Assigning to several variables from items in an iterable, using syntax like ++a, b = [c, d]++—also known as destructuring assignment. This is a common application of _tuple unpacking_.

[[parameter]]parameter:: (((parameters, definition of term)))Functions are declared with 0 or more "formal parameters," which are unbound local variables. When the function is called, the _arguments_ or "actual parameters" passed are bound to those variables. In this book, I tried to use _argument_ to refer to an actual parameter passed to a function, and _parameter_ for a formal parameter in the function declaration. However, that is not always feasible because the terms _parameter_ and _argument_ are used interchangeably all over the Python docs and API. See _argument_.

prime (verb):: ((("prime, definition of term")))Calling `next(coro)` on a coroutine to advance it to its first `yield` expression so that it becomes ready to receive values in succeeding `coro.send(value)` calls.

[[PyPI]]PyPI:: ((("PyPI (The Python Package Index)")))The https://pypi.python.org[Python Package Index], where more than 60,000 packages are available, also known as the _Cheese shop_ (see _Cheese shop_). PyPI is pronounced as "pie-P-eye" to avoid confusion with _PyPy_.

PyPy:: (((PyPy language)))An alternative implementation of the Python programming language using a toolchain that compiles a subset of Python to machine code, so the interpreter source code is actually written in Python. PyPy also includes a JIT to generate machine code for user programs on the fly--like the Java VM does. As of November 2014, PyPy is 6.8 times faster than CPython on average, according to http://speed.pypy.org[published benchmarks]. PyPy is pronounced as "pie-pie" to avoid confusion with _PyPI_.

Pythonic:: ((("Pythonic, definition of term")))Used to praise idiomatic Python code, that makes good use of language features to be concise, readable, and often faster as well. Also said of APIs that enable coding in a way that seems natural to proficient Python programmers. See _idiom_.

receiver:: (((receiver)))The object to which a method call is applied; e.g. the `x` in `x.play()`. The first parameter of the method—conventionally named `self`—is bound to the receiver.

refcount:: ((("reference counting (refcount)")))The reference counter that each CPython object keeps internally in order to determine when it can be destroyed by the garbage collector.

referent:: (((referent objects)))(((objects, referent)))The object that is the target of a reference. This term is most often used to discuss _weak references_.

REPL:: ((("REPL (Read-eval-print-loop)")))Read-eval-print loop, an interactive console, like the standard `python` or alternatives like `ipython`, `bpython`, and Python Anywhere.

sequence:: (((sequences, definition of term)))Generic name for any iterable data structure with a known size (e.g., `len(s)`) and allowing item access via 0-based integer indexes (e.g., `s[0]`). The word _sequence_ has been part of the Python jargon from the start, but only with Python 2.6 was it formalized as an abstract class in `collections.abc.Sequence`.

serialization:: (((serialization)))(((objects, serialization of)))Converting an object from its in-memory structure to a binary or text-oriented format for storage or transmission, in a way that allows the future reconstruction of a clone of the object on the same system or on a different one. The `pickle` module supports serialization of arbitrary Python objects to a binary format.

shallow copy:: (((shallow copies)))(((objects, shallow copies of)))A copy of an object which shares references to all the objects that are attributes of the original object. Contrast with _deep copy_. Also see _aliasing_.

singleton:: (((singletons)))(((objects, singletons)))An object that is the only existing instance of a class--usually not by accident but because the class is designed to prevent creation of more than one instance. There is also a design pattern named Singleton, which is a recipe for coding such classes. The `None` object is a singleton in Python.

slicing:: (((slicing, definition of term)))(((sequences, slicing of)))Producing a subset of a sequence by using the slice notation, e.g., `my_sequence[2:6]`. Slicing usually copies data to produce a new object; in particular, `my_sequence[:]` creates a shallow copy of the entire sequence. But a `memoryview` object can be sliced to produce a new `memoryview` that shares data with the original object.

snake_case:: ((("snake_case")))The convention of writing identifiers by joining words with the underscore character (`_`)—for example, `run_until_complete`. PEP-8 calls this style "lowercase with words separated by underscores" and recommends it for naming functions, methods, arguments, and variables. For packages, PEP-8 recommends concatenating words with no separators. The Python standard library has many examples of `snake_case` identifiers, but also many examples of identifiers with no separation between words (e.g., `getattr`, `classmethod`, `isinstance`, `str.endswith`, etc.). See _CamelCase_.

special method:: (((special methods, definition of term)))((("methods", "special", see="special methods")))A method with a special name such as pass:[<code class="keep-together">__getitem__</code>], spelled with leading and trailing double underscores. Almost all special methods recognized by Python are described in the http://bit.ly/1GsZwss["Data model" chapter] of _The Python Language Reference_, but a few that are used only in specific contexts are documented in other parts of the documentation. For example, the `+__missing__+` method of mappings is mentioned in http://bit.ly/1QS9Ong["4.10. Mapping Types — `dict`"] in _The Python Standard Library_.

storage attribute:: (((storage attributes)))(((attributes, storage)))An attribute in a _managed instance_ used to store the value of an attribute managed by a _descriptor_. See also _managed attribute_.

strong reference:: (((strong references)))(((references, strong)))A reference that keeps an object alive in Python. Contrast with _weak reference_.

subject:: (((pattern matching, subject)))The value of the expression in the `match` clause. Python will try to match the pattern in each `case` clause to the subject.

tuple unpacking:: (((tuple unpacking, definition of term)))Assigning items from an iterable object to a tuple of variables (e.g., `first, second, third == my_list`). This is the usual term used by Pythonistas, but _iterable unpacking_ is gaining traction.

truthy:: (((truthiness)))Any value `x` for which `bool(x)` returns `True`; Python implicitly uses `bool` to evaluate objects in Boolean contexts, such as the expression controlling an `if` or `while` loop. The opposite of _falsy_.

type:: ((("type, definition of term")))Each specific category of program data, defined by a set of possible values and operations on them. Some Python types are close to machine data types (e.g., `float` and `bytes`) while others are extensions (e.g., `int` is not limited to CPU word size, `str` holds multibyte Unicode data points) and very high-level abstractions (e.g., `dict`, `deque`, etc.). Types may be user defined or built into the interpreter (a "built-in" type). Before the watershed type/class unification in Python 2.2, types and classes were different entities, and user-defined classes could not extend built-in types. Since then, built-in types and new-style classes became compatible, and a class is an instance of `type`. In Python 3 all classes are new-style classes. See _class_ and _metaclass_.

unbound method:: (((unbound methods)))(((methods, unbound)))An instance method accessed directly on a class is not bound to an instance; therefore it's said to be an "unbound method." To succeed, a call to an unbound method must explicitly pass an instance of the class as the first argument. That instance will be assigned to the `self` argument in the method. See _bound method_.

uniform access principle:: ((("uniform access principle")))Bertrand Meyer, creator of the Eiffel Language, wrote: "All services offered by a module should be available through a uniform notation, which does not betray whether they are implemented through storage or through computation." Properties and descriptors allow the implementation of the uniform access principle in Python. The lack of a `new` operator, making function calls and object instantiation look the same, is another form of this principle: the caller does not need to know whether the invoked object is a class, a function, or any other callable.

user-defined:: ((("user-defined", "definition of term")))Almost always in the Python docs the word _user_ refers to you and I--programmers who use the Python language--as opposed to the developers who implement a Python interpreter. So the term "user-defined class" means a class written in Python, as opposed to built-in classes written in C, like `str`.

view:: Python 3 views are special data structures returned by the `dict` methods `.keys()`, `.values()`, and `.items()`, providing a dynamic view into the `dict` keys and values without data duplication (which occurs in Python 2 where those methods return lists). All `dict` views are iterable and support the `in` operator. In addition, if the items referenced by the view are all hashable, then the view also implements the `collections.abc.Set` interface. This is the case for all views returned by the `.keys()` method, and for views returned by `.items()` when the values are also hashable.

virtual subclass:: (((virtual subclasses)))(((subclasses, virtual)))A class that does not inherit from a superclass but is registered using `TheSuperClass.register(TheSubClass)`. See documentation for http://bit.ly/1DeDbKf[`abc.ABCMeta.register`].

warlus operator:: (((walrus operator)))Semi-official name for the ++:=++ operator, formally described in https://www.python.org/dev/peps/pep-0572/[PEP 572—Assignment Expressions].

wart:: ((("warts, definition of term")))A misfeature of the language. Andrew Kuchling's famous post "Python warts" has been acknowledged by the _BDFL_ as influential in the decision to break backward-compatibility in the design of Python 3, as most of the failings could not be fixed otherwise. Many of Kuchling's issues were fixed in Python 3. See https://wiki.python.org/moin/PythonWarts[Python Warts] in https://wiki.python.org[wiki.python.org].

weak reference:: (((weak references)))(((references, weak)))A special kind of object reference that does not increase the _referent_ object reference count. Weak references are created with one of the functions and data structures in the `weakref` module.

YAGNI:: "You Ain't Gonna Need It," a slogan to avoid implementing functionality that is not immediately necessary based on assumptions about future needs.

Zen of Python:: Type `import this` into any Python console since version 2.2.
